// nftgen.cpp — see nftgen.h. Native port of nftgen.py; the ip6 filter table
// and the WAN iface set (one WAN, or eth0 + wlan0 for WAN=auto) came after.
#include "nftgen.h"
#include "conntrack.h"
#include "store.h"
#include "sysinfo.h"
#include <cstdio>
#include <cstring>
#include <map>
#include <set>
#include <unistd.h>

namespace nftgen {

// "a", "b" — the elements of an ifname set.
static std::string ifname_elements(const std::vector<std::string>& names) {
    std::string out;
    for (size_t i = 0; i < names.size(); ++i) {
        if (i) out += ", ";
        out += "\"" + names[i] + "\"";
    }
    return out;
}

std::string generate(const std::vector<std::string>& wans, const std::vector<std::string>& lans, bool with_ipv6) {
    auto forwards = store::read_portforwards();
    auto openports = store::read_openports();
    // HaLow modem over SLIP (S31slip): the kernel SLIP driver always names
    // the interface sl0. When the link is configured, the modem gets the
    // same surface as the LAN (its web UI, DNS, MQTT out) and free egress —
    // the WAN postrouting masquerade is source-unrestricted, so NAT needs
    // no extra rule of its own. Invalid conf values simply skip the rules
    // (never inject unvalidated strings into the ruleset).
    auto slip = store::read_slip();
    bool slip_on = slip.enabled == "yes" && store::valid_ipv4(slip.local_ip)
                                     && store::valid_ipv4(slip.peer_ip);

    std::string lan_set = ifname_elements(lans);
    std::string wan_set = ifname_elements(wans);

    std::string L;
    auto add = [&](const std::string& s) { L += s; L += "\n"; };

    add("# Generated by rnsbox nftgen — do not hand-edit.");
    add("# Re-render with: /etc/init.d/S60routing restart\n");
    add("flush ruleset\n");

    add("table ip filter {");
    add("\tset lan_ifaces { type ifname; elements = { " + lan_set + " } }");
    add("\tset wan_ifaces { type ifname; elements = { " + wan_set + " } }\n");

    add("\tchain input {");
    add("\t\ttype filter hook input priority filter; policy drop;");
    add("\t\tct state invalid drop");
    add("\t\tct state established,related accept");
    add("\t\tiifname \"lo\" accept");
    add("\t\ticmp type echo-request limit rate 10/second accept");
    add("\t\t# LAN: full management surface (HTTP UI on :80, DHCP/DNS, SSH, etc.)");
    add("\t\tiifname @lan_ifaces accept");
    if (slip_on) {
        add("\t\t# HaLow modem over SLIP: management surface like the LAN");
        add("\t\tiifname \"sl0\" accept");
    }
    if (!forwards.empty()) {
        add("\t\t# port forwards whose target is the device itself (DNAT -> INPUT)");
        add("\t\tiifname @wan_ifaces ct status dnat accept");
    }
    // route_localnet is on for the WAN ifaces (S60routing), for forwards to
    // 127.x; anything else addressed to loopback from the WAN never reaches
    // an open port (a WiFi-client neighbour could otherwise hit a service
    // bound only to 127.0.0.1).
    add("\t\tiifname @wan_ifaces ip daddr 127.0.0.0/8 drop");
    if (!openports.empty()) {
        std::map<std::string, std::set<int>> pp;   // proto -> sorted unique ports
        for (const auto& op : openports) pp[op.proto].insert(op.port);
        // The HaLow modem page is the same portal on a second uhttpd port (main.cpp
        // MODEM_PORT, S81router -p :8081): opening the web UI (tcp 80) on the WAN
        // opens it too, so the "Open modem web UI" link keeps working from the WAN.
        if (pp.count("tcp") && pp["tcp"].count(80)) pp["tcp"].insert(8081);
        for (const auto& kv : pp) {
            std::string ports;
            for (auto it = kv.second.begin(); it != kv.second.end(); ++it) {
                if (it != kv.second.begin()) ports += ", ";
                ports += std::to_string(*it);
            }
            add("\t\t# user-managed open ports");
            add("\t\tiifname @wan_ifaces " + kv.first + " dport { " + ports + " } accept");
        }
    }
    add("\t}\n");

    add("\tchain forward {");
    add("\t\ttype filter hook forward priority filter; policy drop;");
    add("\t\tct state invalid drop");
    add("\t\tct state established,related accept");
    add("\t\t# LAN -> WAN (free egress)");
    add("\t\tiifname @lan_ifaces oifname @wan_ifaces accept");
    if (slip_on) {
        add("\t\t# HaLow modem over SLIP: free egress (telemetry, RNS uplink)");
        add("\t\tiifname \"sl0\" oifname @wan_ifaces accept");
    }
    if (!forwards.empty()) {
        add("\t\t# WAN -> LAN, post-DNAT (port forward destinations)");
        for (const auto& fw : forwards)
            add("\t\tiifname @wan_ifaces oifname @lan_ifaces ip daddr " + fw.lan_ip + " " +
                fw.proto + " dport " + std::to_string(fw.lan_port) + " accept");
    }
    add("\t}\n");

    add("\tchain output { type filter hook output priority filter; policy accept; }");
    add("}\n");

    add("table ip nat {");
    add("\tset wan_ifaces { type ifname; elements = { " + wan_set + " } }\n");   // sets are per table
    add("\tchain prerouting {");
    add("\t\ttype nat hook prerouting priority dstnat; policy accept;");
    for (const auto& fw : forwards)
        add("\t\tiifname @wan_ifaces " + fw.proto + " dport " + std::to_string(fw.wan_port) +
            " dnat to " + fw.lan_ip + ":" + std::to_string(fw.lan_port));
    add("\t}\n");
    add("\tchain postrouting {");
    add("\t\ttype nat hook postrouting priority srcnat; policy accept;");
    // The ct mark tags the flow as NATed to this uplink, so `rnsbox-portal
    // ctflush` can drop just these when WAN=auto moves to the other one.
    char mark[16];
    snprintf(mark, sizeof mark, "0x%08x", conntrack::WAN_NAT_MARK);
    add(std::string("\t\toifname @wan_ifaces ct mark set ct mark or ") + mark + " masquerade");
    add("\t}");
    add("}");

    if (with_ipv6) {
        // IPv6 is only there for Reticulum's AutoInterface on the LAN iface
        // (br-lan; fe80:: link-local + ff12:: multicast; UDP 29716/29717/42671)
        // and S09ipv6 disables it on every other iface, bridge ports included.
        // This table is the second layer: nothing but lo + the LAN reaches the
        // box over IPv6, nothing is routed.
        add("");
        add("table ip6 filter {");
        add("\tset lan_ifaces { type ifname; elements = { " + lan_set + " } }\n");

        add("\tchain input {");
        add("\t\ttype filter hook input priority filter; policy drop;");
        add("\t\tct state invalid drop");
        add("\t\tct state established,related accept");
        add("\t\tiifname \"lo\" accept");
        add("\t\t# neighbour discovery + MLD (multicast group joins) on the LAN;");
        add("\t\t# conntrack leaves these untracked, so they need an explicit accept");
        add("\t\tiifname @lan_ifaces icmpv6 type { nd-neighbor-solicit, nd-neighbor-advert, "
            "mld-listener-query, mld-listener-report, mld-listener-done, mld2-listener-report } accept");
        add("\t\t# LAN: full surface (Reticulum AutoInterface discovery/data, SSH, ...)");
        add("\t\tiifname @lan_ifaces accept");
        add("\t}\n");

        add("\tchain forward {");
        add("\t\ttype filter hook forward priority filter; policy drop;");
        add("\t}\n");

        add("\tchain output { type filter hook output priority filter; policy accept; }");
        add("}");
    }
    return L;
}

// "a, b,c" -> {"a", "b", "c"} (comma-separated, trimmed, empty parts dropped).
static std::vector<std::string> split_list(const std::string& s) {
    std::vector<std::string> out;
    size_t i = 0;
    while (i < s.size()) {
        size_t c = s.find(',', i);
        if (c == std::string::npos) c = s.size();
        std::string t = s.substr(i, c - i);
        size_t a = t.find_first_not_of(" \t");
        size_t b = t.find_last_not_of(" \t");
        if (a != std::string::npos) out.push_back(t.substr(a, b - a + 1));
        i = c + 1;
    }
    return out;
}

int cli_main(int argc, char** argv) {
    std::string wan, lan;
    // ip6 table only on a kernel that has IPv6 (the rootfs can outlive the
    // kernel it shipped with) — nft would reject `table ip6` otherwise and
    // S60routing's nft -c would throw away the whole ruleset.
    bool v6 = access("/proc/sys/net/ipv6", F_OK) == 0;
    for (int i = 2; i < argc; ++i) {   // argv[1] == "nftgen"
        if (!strcmp(argv[i], "--wan") && i + 1 < argc) wan = argv[++i];
        else if (!strcmp(argv[i], "--lan") && i + 1 < argc) lan = argv[++i];
        else if (!strcmp(argv[i], "--no-ipv6")) v6 = false;
    }
    if (lan.empty()) lan = sysinfo::lan_iface();
    std::vector<std::string> wans = split_list(wan), lans = split_list(lan);
    if (wans.empty()) { fprintf(stderr, "usage: rnsbox-portal nftgen --wan <iface>[,iface] [--lan a,b] [--no-ipv6]\n"); return 2; }
    std::string out = generate(wans, lans, v6);
    // S60routing trusts this exit status: a short write (ENOSPC) must fail,
    // or an empty file passes `nft -c` (empty batch) and gets installed.
    if (fwrite(out.data(), 1, out.size(), stdout) != out.size() || fflush(stdout) != 0) {
        perror("nftgen: write");
        return 1;
    }
    return 0;
}

}  // namespace nftgen
