// nftgen.cpp — see nftgen.h. Native port of nftgen.py; output is byte-identical.
#include "nftgen.h"
#include "store.h"
#include <cstdio>
#include <cstring>
#include <map>
#include <set>

namespace nftgen {

std::string generate(const std::string& wan, const std::vector<std::string>& lans) {
    auto forwards = store::read_portforwards();
    auto openports = store::read_openports();

    std::string lan_set;
    for (size_t i = 0; i < lans.size(); ++i) {
        if (i) lan_set += ", ";
        lan_set += "\"" + lans[i] + "\"";
    }

    std::string L;
    auto add = [&](const std::string& s) { L += s; L += "\n"; };

    add("# Generated by rnsbox nftgen — do not hand-edit.");
    add("# Re-render with: /etc/init.d/S60routing restart\n");
    add("flush ruleset\n");

    add("table ip filter {");
    add("\tset lan_ifaces { type ifname; elements = { " + lan_set + " } }\n");

    add("\tchain input {");
    add("\t\ttype filter hook input priority filter; policy drop;");
    add("\t\tct state invalid drop");
    add("\t\tct state established,related accept");
    add("\t\tiifname \"lo\" accept");
    add("\t\ticmp type echo-request limit rate 10/second accept");
    add("\t\t# LAN: full management surface (HTTP UI on :80, DHCP/DNS, SSH, etc.)");
    add("\t\tiifname @lan_ifaces accept");
    if (!forwards.empty()) {
        add("\t\t# port forwards whose target is the device itself (DNAT -> INPUT)");
        add("\t\tiifname \"" + wan + "\" ct status dnat accept");
    }
    if (!openports.empty()) {
        std::map<std::string, std::set<int>> pp;   // proto -> sorted unique ports
        for (const auto& op : openports) pp[op.proto].insert(op.port);
        for (const auto& kv : pp) {
            std::string ports;
            for (auto it = kv.second.begin(); it != kv.second.end(); ++it) {
                if (it != kv.second.begin()) ports += ", ";
                ports += std::to_string(*it);
            }
            add("\t\t# user-managed open ports");
            add("\t\tiifname \"" + wan + "\" " + kv.first + " dport { " + ports + " } accept");
        }
    }
    add("\t}\n");

    add("\tchain forward {");
    add("\t\ttype filter hook forward priority filter; policy drop;");
    add("\t\tct state invalid drop");
    add("\t\tct state established,related accept");
    add("\t\t# LAN -> WAN (free egress)");
    add("\t\tiifname @lan_ifaces oifname \"" + wan + "\" accept");
    if (!forwards.empty()) {
        add("\t\t# WAN -> LAN, post-DNAT (port forward destinations)");
        for (const auto& fw : forwards)
            add("\t\tiifname \"" + wan + "\" oifname @lan_ifaces ip daddr " + fw.lan_ip + " " +
                fw.proto + " dport " + std::to_string(fw.lan_port) + " accept");
    }
    add("\t}\n");

    add("\tchain output { type filter hook output priority filter; policy accept; }");
    add("}\n");

    add("table ip nat {");
    add("\tchain prerouting {");
    add("\t\ttype nat hook prerouting priority dstnat; policy accept;");
    for (const auto& fw : forwards)
        add("\t\tiifname \"" + wan + "\" " + fw.proto + " dport " + std::to_string(fw.wan_port) +
            " dnat to " + fw.lan_ip + ":" + std::to_string(fw.lan_port));
    add("\t}\n");
    add("\tchain postrouting {");
    add("\t\ttype nat hook postrouting priority srcnat; policy accept;");
    add("\t\toifname \"" + wan + "\" masquerade");
    add("\t}");
    add("}");
    return L;
}

int cli_main(int argc, char** argv) {
    std::string wan, lan = "usb0";
    for (int i = 2; i < argc; ++i) {   // argv[1] == "nftgen"
        if (!strcmp(argv[i], "--wan") && i + 1 < argc) wan = argv[++i];
        else if (!strcmp(argv[i], "--lan") && i + 1 < argc) lan = argv[++i];
    }
    if (wan.empty()) { fprintf(stderr, "usage: rnsbox-portal nftgen --wan <iface> [--lan a,b]\n"); return 2; }
    std::vector<std::string> lans;
    size_t i = 0;
    while (i < lan.size()) {
        size_t c = lan.find(',', i);
        if (c == std::string::npos) c = lan.size();
        std::string t = lan.substr(i, c - i);
        // trim
        size_t a = t.find_first_not_of(" \t");
        size_t b = t.find_last_not_of(" \t");
        if (a != std::string::npos) lans.push_back(t.substr(a, b - a + 1));
        i = c + 1;
    }
    std::string out = generate(wan, lans);
    fwrite(out.data(), 1, out.size(), stdout);
    return 0;
}

}  // namespace nftgen
